# Generated by Django 5.0.2 on 2024-02-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_alter_reservebook_date_of_devolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservebook',
            name='number_of_reserve',
        ),
    ]
