# Generated by Django 5.0.2 on 2024-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_reservebook_date_of_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservebook',
            name='date_of_reserve',
            field=models.DateField(blank=True, null=True, verbose_name='Data da reserva'),
        ),
    ]
