# Generated by Django 5.0.2 on 2024-02-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_alter_reservebook_date_of_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservebook',
            name='date_of_devolution',
        ),
        migrations.AddField(
            model_name='reservebook',
            name='devolution',
            field=models.BooleanField(default=False, verbose_name='Devolvido'),
        ),
        migrations.AddField(
            model_name='reservebook',
            name='devolution_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de devolução'),
        ),
    ]
