# Generated by Django 5.0.2 on 2024-03-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_remove_reservebook_date_of_devolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservebook',
            name='renew_book',
            field=models.BooleanField(default=False, verbose_name='Renovado'),
        ),
        migrations.AddField(
            model_name='reservebook',
            name='return_date_after_renew',
            field=models.DateField(blank=True, null=True, verbose_name='Data de devolução após a renovação'),
        ),
    ]
