# Generated by Django 5.0.2 on 2024-03-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_reservebook_quantity_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservebook',
            name='quantity_reserve',
        ),
    ]
