# Generated by Django 5.0.2 on 2024-02-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usercustom_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='has_a_scheduling',
            field=models.BooleanField(default=False, verbose_name='Possui Agendamento?'),
        ),
    ]
